spring:
  datasource:
    url: jdbc:h2:mem:tacocloud;NON_KEYWORDS=user
    generate-unique-name: false
    name: tacocloud
server:
  port: 8443
  ssl:
    key-store: file:///C:/Users/Administrator/mykeys.jks
    key-store-password: letmein
    key-password: letmein